name: Actions Automatic Post-Release

on:
  workflow_run:
    workflows: [Release]
    types: [completed]

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@v2