name: Release
on: 
  workflow_dispatch:
jobs:
  Release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.14
      - name: Get Metadata
        uses: juliojimenez/yamler@v0
        id: metadata
        with:
          yaml-file: metadata.yml
      - name: Check if Repository Description Matches Metadata
        run: |
          $Description = "${{ steps.metadata.outputs.description }}"
          $RepoSplat = @{
            Uri = "https://api.github.com/repos/$env:GITHUB_REPOSITORY"
            Method = "GET"
            Headers = @{
              Accept = "application/vnd.github.v3+json"
            }
          }
          $RepoData = Invoke-RestMethod @RepoSplat

          if ($RepoData.Description -ne $Description) {
            throw "Repo description does not match metadata! Please fix and re-run."
          }
      - name: Update README Description
        uses: VisualBean/reactive-readme@v1
        with:
          section: description
          value: ${{ steps.metadata.outputs.description }}
      - name: Update README Inputs/Outputs
        uses: mdvorak/update-action-readme@v1
      - name: Push Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.gitversion.outputs.SemVer }}
      - name: Update Changelog
        id: changelog
        uses: natescherer/changelog-management-action@main
        with:
          mode: release
          releaseversion: ${{ steps.gitversion.outputs.SemVer }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update changelog for release
          title: Changelog update by create-pull-request action
          delete-branch: true
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            # Release v${{ steps.gitversion.outputs.MajorMinorPatch }}
            ${{ steps.metadata.outputs.releaseheader }}

            ## Changes
            ${{ steps.changelog.outputs.releasenotes }}
          draft: true