name: Release
on: 
  workflow_dispatch:
jobs:
  Release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.14
      - name: Push Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.gitversion.outputs.SemVer }}
      - name: Update Changelog
        id: updatechangelog
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
          Install-Module ChangelogManagement
          Update-Changelog -Path $env:GITHUB_WORKSPACE/CHANGELOG.md -ReleaseVersion $env:CALCVERSION -LinkMode Automatic -LinkPattern @{FirstRelease = "https://github.com/$env:GITHUB_REPOSITORY/tree/v{CUR}";NormalRelease = "https://github.com/$env:GITHUB_REPOSITORY/compare/v{PREV}..v{CUR}";Unreleased = "https://github.com/$env:GITHUB_REPOSITORY/compare/v{CUR}..HEAD"}
        env:
          CALCVERSION: ${{ steps.gitversion.outputs.SemVer }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update changelog for release
          title: Changelog update by create-pull-request action
          delete-branch: true
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true